export interface winnerProps {}

export const WinnerContent: winnerProps[] = [
    "adekunle christiana oreofe",
    "Adeniyi Oluwabukola Adedamola",
    "Akinwolere Valentine",
    "Anita Emeji",
    "Akanbi Abdulqoweey",
    "Anuoluwapo Kuye",
    "Arthur Akalazu",
    "Boluwatife Ajayi",
    "Badejo Motunrayo Mariam",
    "Corlet",
    "Chika Gloria",
    "Christopher Kalaro",
    "Daniel",
    "Cornelius Ajewole",
    "Daniel Ogenna",
    "Eunice Eze",
    "Elijah Dotun",
    "Emmanuel Chira",
    "Imaobong Elijah",
    "Esther Chinonye Ebinim",
    "Juwon Oloruntoba",
    "Obinna Ihe",
    "Ifeanyi Oji",
    "Kanu Ikechukwu",
    "Henry Nzelu",
    "Stephen Olushola",
    "Popoola Abdussalam",
    "Khadijat ajadi",
    "Temitope Oni",
    "Oseyili Joel",
    "Julius OluwaDamilola",
    "Odekunle Toluwabori Joseph",
    "Iyasele David Michael",
    "Layole Sumayyah Olakunmi",
    "Yinka Adeoye",
    "uche udo ibe",
    "Tolulope Awolusi",
    "Uche Uwam",
    "Peter Agbai",
    "Michael Olatunji",
    "Oluwatosin Adewakun",
    "Yusuf Ridwan",
    "Uchenna Chinazaekpere",
    "Lawal Sofiyat Olabisi",
    "Wisdom Abiodun",
    "Octavian",
    "Precious Adetunji",
    "Olumide Balogun",
    "Edor Emmanuel",
    "Victor Chaman"
]  
